### PR TITLE
remove this project from checkmarx scanning (no source code)

### PR DESCRIPTION
**Pull request by jensh007**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Change pipeline definition so that this project is excluded from checkmarx scans as ist contains no source code

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
This PR proposes changes that would break the pipeline definition:
```
<invalid YAML>: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 40, column 1:
    		  component_labels:
    ^
```

**Comment by gardener-robot-ci-3** [comment]
This PR proposes changes that would break the pipeline definition:
```
<invalid YAML>: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 40, column 1:
    		  component_labels:
    ^
```

**Comment by gardener-robot-ci-3** [comment]
This PR proposes changes that would break the pipeline definition:
```
<invalid YAML>: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 40, column 1:
    		  component_labels:
    ^
```

**Comment by gardener-robot-ci-3** [comment]
The pipeline-definition has been fixed.

**Review by shreyas-s-rao — APPROVED** [review]
@jensh007 Thanks a lot for the PR. 
/lgtm
/invite @abdasgupta

**Pull request merged**
